CREATE TABLE IF NOT EXISTS config_meta (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL, prompt TEXT NOT NULL, decision TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS models (id TEXT PRIMARY KEY CHECK(id <> 'auto'), provider_id TEXT NOT NULL REFERENCES providers(id), body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency (principal TEXT NOT NULL, key TEXT NOT NULL, digest TEXT NOT NULL, result TEXT NOT NULL, expires_ns INTEGER NOT NULL, PRIMARY KEY(principal,key));
