import {useState} from 'react';
import {PageTitle,Empty,ErrorBox,Loading,Pager,useRead,type PageProps} from './components';
import {text} from './i18n';
export type Model={id:string;description:string;enabled:boolean;provider_id:string;upstream_name:string;location:string;capabilities:Record<string,unknown>;[key:string]:unknown};
export type Resource={version:number;resource:Model};
export function Overview(props:PageProps){
 const {lang}=props;const [refresh,setRefresh]=useState(0);const {data,error,loading}=useRead<{ready:boolean;version:number;enabled_models:number;records_degraded:boolean}>(props,'status.get',{},refresh);
 return <><PageTitle title={text(lang,'A clear view of your router.','路由状态，一目了然。')} description={text(lang,'One instance. Shared controls for people and agents.','一个实例，Agent 与人类共用管理能力。')}><button onClick={()=>setRefresh(x=>x+1)}>{text(lang,'Refresh','刷新')}</button></PageTitle>{loading?<Loading/>:error?<ErrorBox error={error} lang={lang}/>:data&&<><section className="status-panel"><div className="eyebrow">{text(lang,'INSTANCE STATUS','实例状态')}</div><h2><span className={'dot '+(data.ready?'green':'')}/>{text(lang,data.ready?'Ready':'Needs configuration',data.ready?'已就绪':'待配置')}</h2><p>{text(lang,'Configuration readiness, not an upstream health check.','表示配置就绪，不代表上游健康检查已通过。')}</p><div className="facts"><div><small>{text(lang,'Enabled models','已启用模型')}</small><strong>{data.enabled_models}</strong></div><div><small>{text(lang,'Configuration version','配置版本')}</small><strong>v{data.version}</strong></div><div><small>{text(lang,'Decision backend','决策后端')}</small><strong>Jev</strong></div></div></section>{data.records_degraded&&<div className="notice error">{text(lang,'Routing record storage is degraded. Generation can continue, but records may be missing.','路由记录存储已降级。生成仍可继续，但记录可能缺失。')}</div>}<section className="guidance"><h3>{text(lang,'Built for agents. Open to you.','Agent 优先，人类随时辅助。')}</h3><p>{text(lang,'Configure providers and models through the CLI. Use this workspace to refine descriptions, adjust routing preferences and inspect results.','通过 CLI 配置供应商和模型，在这里调整模型描述与路由偏好，查看调用结果。')}</p><code>jev-router schema</code><code>jev-router schema models.put</code></section></>}</>;
}
export function Models(props:PageProps&{canEdit:boolean;onDirty:(dirty:boolean)=>void;renderEditor?:(id:string)=>React.ReactNode}){
 const{lang}=props;const[cursors,setCursors]=useState(['']);const[selected,setSelected]=useState('');const{data,error,loading}=useRead<{items:Model[];next_cursor:string;version:number}>(props,'models.list',{cursor:cursors.at(-1),limit:20});
 return <><PageTitle title={text(lang,'Models','模型')} description={text(lang,'Describe what each model does best. Capabilities stay explicit.','用描述表达模型专长，用能力声明约束输入。')}/>{selected?<><button className="back" onClick={()=>{if(window.confirm(text(lang,'Return to the model list? Unsaved changes will be lost.','返回模型列表？未保存的修改将丢失。'))){props.onDirty(false);setSelected('')}}}>← {text(lang,'All models','全部模型')}</button>{props.renderEditor?props.renderEditor(selected):<ModelRead {...props} id={selected}/>}</>:loading?<Loading/>:error?<ErrorBox error={error} lang={lang}/>:data&&<><div className="section-label">{text(lang,'MODEL REGISTRY','模型列表')} <span>v{data.version}</span></div>{!data.items.length?<Empty title={text(lang,'No models configured','尚未配置模型')} detail={text(lang,'Use jev-router schema models.put to get started.','使用 jev-router schema models.put 开始配置。')}/>:<div className="model-list">{data.items.map(m=><button key={m.id} className="model-row" onClick={()=>setSelected(m.id)}><div className="model-monogram">{m.id.slice(0,1).toUpperCase()}</div><div className="model-copy"><h3>{m.id}<span className={'badge '+(m.enabled?'enabled':'')}>{text(lang,m.enabled?'Enabled':'Disabled',m.enabled?'已启用':'已禁用')}</span></h3><p>{m.description||text(lang,'No description yet','暂无描述')}</p><small>{m.provider_id} / {m.upstream_name}</small></div><span aria-hidden>↗</span></button>)}</div>}<Pager lang={lang} next={data.next_cursor} back={cursors.length>1} onBack={()=>setCursors(x=>x.slice(0,-1))} onNext={()=>setCursors(x=>[...x,data.next_cursor])}/></>}</>;
}
export function ModelRead(props:PageProps&{id:string}){const{data,error,loading}=useRead<Resource>(props,'models.get',{id:props.id});return loading?<Loading/>:error?<ErrorBox error={error} lang={props.lang}/>:<pre>{JSON.stringify(data?.resource,null,2)}</pre>}
export function PromptRead(props:PageProps){const{data,error,loading}=useRead<{text:string;version:number}>(props,'prompt.get');return <><PageTitle title={text(props.lang,'Routing prompt','路由提示词')} description={text(props.lang,'One balanced template. Your routing preferences.','一份均衡模板，表达你的选模偏好。')}/>{loading?<Loading/>:error?<ErrorBox error={error} lang={props.lang}/>:<pre className="prompt-read">{data?.text}</pre>}</>}
export function Records(props:PageProps){
 const{lang}=props;const[cursors,setCursors]=useState(['']);const[refresh,setRefresh]=useState(0);const{data,error,loading}=useRead<{records:Array<Record<string,unknown>>;next_cursor:string}>(props,'records.list',{cursor:cursors.at(-1),limit:20},refresh);
 return <><PageTitle title={text(lang,'Routing records','路由记录')} description={text(lang,'Selection and execution metadata. No conversation content.','查看选择与执行元数据，不保存对话内容。')}><button onClick={()=>{setCursors(['']);setRefresh(x=>x+1)}}>{text(lang,'Refresh','刷新')}</button></PageTitle>{loading?<Loading/>:error?<ErrorBox error={error} lang={lang}/>:data&&!data.records.length?<Empty title={text(lang,'No routing records yet','暂无路由记录')} detail={text(lang,'Requests sent through the inference API will appear here.','通过推理 API 发起请求后，可在这里查看记录。')}/>:data&&<><div className="table-wrap"><table><thead><tr>{[text(lang,'Request / time','请求 / 时间'),text(lang,'Selected model','选定模型'),text(lang,'Path','选择路径'),text(lang,'Duration','耗时'),text(lang,'Result','结果')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.records.map(r=><tr key={String(r.request_id)}><td><details><summary className="request-id">{String(r.request_id)}</summary><pre>{JSON.stringify(r,null,2)}</pre></details><small>{String(r.created_at)}</small></td><td>{String(r.model_id||'—')}</td><td><span className="badge">{String(r.path||'—')}</span></td><td>{typeof r.decision_ms==='number'&&typeof r.generation_ms==='number'?`${r.decision_ms+r.generation_ms} ms`:'—'}</td><td>{String(r.outcome)}</td></tr>)}</tbody></table></div><Pager lang={lang} next={data.next_cursor} back={cursors.length>1} onNext={()=>setCursors(x=>[...x,data.next_cursor])} onBack={()=>setCursors(x=>x.slice(0,-1))}/></>}</>;
}
